name: Jira Issue Check

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  check-jira-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for Jira issue key
        run: |
          #!/bin/bash
          
          # Define regular expression to match Jira issue keys
          JIRA_REGEX='PAR-[0-9]+'
          
          # Function to check for Jira issue keys in commit messages
          check_jira_issue() {
              # Loop through all commit messages
              while read -r line; do
                  # Check if the line contains a valid Jira issue key
                  if ! [[ $line =~ $JIRA_REGEX ]]; then
                      echo "Error: Commit message must include a Jira issue key (e.g., PAR-123)."
                      exit 1
                  fi
              done < <(git log --format=%s "$GITHUB_SHA" ^$GITHUB_SHA^)
          }
          
          # Check for Jira issue keys in commit messages
          check_jira_issue
