name: CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: |
        npm run build | tee build.log
      env:
        NODE_ENV: production

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        
    - name: Extract Authors from Merged Commits
      id: extract_merged_authors
      run: |
        # Find the merge commit
        MERGE_COMMIT=$(git log --merges --first-parent -n 1 --pretty=format:"%H")
        # Find the last commit on the dev branch
        DEV_BRANCH_HEAD=$(git rev-parse dev)
        # Extract authors between merge commit and dev branch head
        AUTHORS=$(git log --pretty=format:"%ae" $MERGE_COMMIT..$DEV_BRANCH_HEAD | sort -u)
        echo "::set-output name=authors::$AUTHORS"

        - name: Send Success Email
          if: success()
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com
            server_port: 587
            username: nikkhiilgupta@gmail.com
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: "✅ CI/CD Pipeline Status: Success - ${{ github.repository }} (${{ github.sha }})"
            to: ${{ steps.extract_merged_authors.outputs.authors }}
            cc: email@example.com  # Add CC recipients here
            from: nikkhiilgupta@gmail.com
            body: |
              The CI/CD pipeline status for commit SHA: ${{ github.sha }} in repository ${{ github.repository }} is: Success.
            attachments: |
              build.log
  
        - name: Send Failure Email
          if: failure()
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com
            server_port: 587
            username: nikkhiilgupta@gmail.com
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: "❌ CI/CD Pipeline Status: Failure - ${{ github.repository }} (${{ github.sha }})"
            to: ${{ steps.extract_merged_authors.outputs.authors }}
            cc: email@example.com  # Add CC recipients here
            from: nikkhiilgupta@gmail.com
            body: |
              The CI/CD pipeline status for commit SHA: ${{ github.sha }} in repository ${{ github.repository }} is: Failure.
            attachments: |
              build.log
